"""LinkedIn automation adapters."""

from job_applier.infrastructure.linkedin.auth import (
    LinkedInAuthError,
    LinkedInCredentials,
    LinkedInSessionManager,
)
from job_applier.infrastructure.linkedin.easy_apply import (
    EasyApplyExecutionResult,
    EasyApplyStep,
    LinkedInEasyApplyError,
    LinkedInEasyApplySubmitter,
    PlaywrightLinkedInEasyApplyExecutor,
)
from job_applier.infrastructure.linkedin.question_resolution import (
    EasyApplyField,
    GeneratedAnswer,
    LinkedInAnswerResolver,
    LinkedInQuestionClassifier,
    LinkedInQuestionExtractor,
    OpenAIResponsesAnswerGenerator,
    QuestionClassification,
    ResolvedFieldValue,
    normalize_key,
    normalize_text,
    pick_option,
)
from job_applier.infrastructure.linkedin.recruiter_connect import (
    LinkedInRecruiterCandidateFinder,
    OpenAIResponsesRecruiterMessageGenerator,
    PlaywrightRecruiterConnector,
    RecruiterCandidate,
    RecruiterConnectAttempt,
    RecruiterMessageGenerator,
    build_recruiter_message_template,
    finalize_recruiter_message,
    select_recruiter_candidate,
)
from job_applier.infrastructure.linkedin.search import (
    LINKEDIN_JOBS_URL,
    LinkedInCollectedJob,
    LinkedInJobFetcher,
    LinkedInJobParser,
    LinkedInSearchCriteria,
    LinkedInSearchError,
    PlaywrightLinkedInJobsClient,
    build_paginated_search_url,
    build_search_criteria,
    infer_seniority,
    infer_workplace_type,
)

__all__ = [
    "EasyApplyExecutionResult",
    "EasyApplyField",
    "EasyApplyStep",
    "GeneratedAnswer",
    "LINKEDIN_JOBS_URL",
    "LinkedInAuthError",
    "LinkedInAnswerResolver",
    "LinkedInCollectedJob",
    "LinkedInCredentials",
    "LinkedInEasyApplyError",
    "LinkedInEasyApplySubmitter",
    "LinkedInJobFetcher",
    "LinkedInJobParser",
    "LinkedInQuestionClassifier",
    "LinkedInQuestionExtractor",
    "LinkedInRecruiterCandidateFinder",
    "LinkedInSearchCriteria",
    "LinkedInSearchError",
    "LinkedInSessionManager",
    "OpenAIResponsesAnswerGenerator",
    "OpenAIResponsesRecruiterMessageGenerator",
    "PlaywrightLinkedInEasyApplyExecutor",
    "PlaywrightLinkedInJobsClient",
    "PlaywrightRecruiterConnector",
    "QuestionClassification",
    "ResolvedFieldValue",
    "RecruiterCandidate",
    "RecruiterConnectAttempt",
    "RecruiterMessageGenerator",
    "build_paginated_search_url",
    "build_recruiter_message_template",
    "build_search_criteria",
    "finalize_recruiter_message",
    "infer_seniority",
    "infer_workplace_type",
    "normalize_key",
    "normalize_text",
    "pick_option",
    "select_recruiter_candidate",
]
