"""LinkedIn automation adapters."""

from job_applier.infrastructure.linkedin.auth import (
    LinkedInAuthError,
    LinkedInCredentials,
    LinkedInSessionManager,
)
from job_applier.infrastructure.linkedin.browser_agent import (
    BrowserAgentAction,
    BrowserAgentElement,
    BrowserAgentSnapshot,
    BrowserAutomationError,
    OpenAIResponsesBrowserAgent,
    has_manual_intervention_cues,
    parse_browser_action,
)
from job_applier.infrastructure.linkedin.easy_apply import (
    EasyApplyExecutionResult,
    EasyApplyStep,
    LinkedInEasyApplyError,
    LinkedInEasyApplySubmitter,
    PlaywrightLinkedInEasyApplyExecutor,
)
from job_applier.infrastructure.linkedin.playwright_mcp import (
    OpenAIResponsesPlaywrightMcpAgent,
    PlaywrightMcpAction,
    PlaywrightMcpClient,
    PlaywrightMcpError,
    PlaywrightMcpHttpClient,
    PlaywrightMcpStdioClient,
    extract_mcp_text_content,
    is_local_playwright_mcp_url,
    normalize_playwright_mcp_url,
    parse_mcp_response_body,
    parse_playwright_mcp_action,
)
from job_applier.infrastructure.linkedin.playwright_mcp import (
    has_manual_intervention_cues as has_playwright_mcp_manual_intervention_cues,
)
from job_applier.infrastructure.linkedin.question_resolution import (
    EasyApplyField,
    GeneratedAnswer,
    LinkedInAnswerResolver,
    LinkedInQuestionClassifier,
    LinkedInQuestionExtractor,
    OpenAIResponsesAnswerGenerator,
    QuestionClassification,
    ResolvedFieldValue,
    normalize_key,
    normalize_text,
    pick_option,
)
from job_applier.infrastructure.linkedin.recruiter_connect import (
    LinkedInRecruiterCandidateFinder,
    OpenAIResponsesRecruiterMessageGenerator,
    PlaywrightRecruiterConnector,
    RecruiterCandidate,
    RecruiterConnectAttempt,
    RecruiterMessageGenerator,
    build_recruiter_message_template,
    finalize_recruiter_message,
    select_recruiter_candidate,
)
from job_applier.infrastructure.linkedin.search import (
    LINKEDIN_JOBS_URL,
    LinkedInCollectedJob,
    LinkedInJobFetcher,
    LinkedInJobParser,
    LinkedInSearchCriteria,
    LinkedInSearchError,
    PlaywrightLinkedInJobsClient,
    build_paginated_search_url,
    build_search_criteria,
    infer_seniority,
    infer_workplace_type,
)

__all__ = [
    "BrowserAgentAction",
    "BrowserAgentElement",
    "BrowserAgentSnapshot",
    "BrowserAutomationError",
    "EasyApplyExecutionResult",
    "EasyApplyField",
    "EasyApplyStep",
    "GeneratedAnswer",
    "LINKEDIN_JOBS_URL",
    "LinkedInAuthError",
    "LinkedInAnswerResolver",
    "LinkedInCollectedJob",
    "LinkedInCredentials",
    "LinkedInEasyApplyError",
    "LinkedInEasyApplySubmitter",
    "LinkedInJobFetcher",
    "LinkedInJobParser",
    "LinkedInQuestionClassifier",
    "LinkedInQuestionExtractor",
    "LinkedInRecruiterCandidateFinder",
    "LinkedInSearchCriteria",
    "LinkedInSearchError",
    "LinkedInSessionManager",
    "OpenAIResponsesAnswerGenerator",
    "OpenAIResponsesBrowserAgent",
    "OpenAIResponsesPlaywrightMcpAgent",
    "OpenAIResponsesRecruiterMessageGenerator",
    "PlaywrightLinkedInEasyApplyExecutor",
    "PlaywrightLinkedInJobsClient",
    "PlaywrightMcpAction",
    "PlaywrightMcpClient",
    "PlaywrightMcpError",
    "PlaywrightMcpHttpClient",
    "PlaywrightMcpStdioClient",
    "PlaywrightRecruiterConnector",
    "QuestionClassification",
    "ResolvedFieldValue",
    "RecruiterCandidate",
    "RecruiterConnectAttempt",
    "RecruiterMessageGenerator",
    "build_paginated_search_url",
    "build_recruiter_message_template",
    "build_search_criteria",
    "extract_mcp_text_content",
    "finalize_recruiter_message",
    "has_manual_intervention_cues",
    "has_playwright_mcp_manual_intervention_cues",
    "infer_seniority",
    "infer_workplace_type",
    "is_local_playwright_mcp_url",
    "normalize_key",
    "normalize_playwright_mcp_url",
    "normalize_text",
    "parse_mcp_response_body",
    "parse_browser_action",
    "parse_playwright_mcp_action",
    "pick_option",
    "select_recruiter_candidate",
]
